### PR TITLE
Chore add publish npm

### PR DESCRIPTION
**Pull request by tophercf**
- add npm as a package manager to utilize for npm module publishing
- update `beta` releases to ensure there aren't collisions if a PR is updated based on feedback. This will increment the beta by 1.
testing results: https://www.npmjs.com/package/@flexbase/http-client-middleware
Screen Shot 2022-07-02 at 8 31 14 PM

### CODE REVIEW

**Comment by tophercf** [comment]
tested and validated in `http-client-middleware` repo:
- build workflow for `yarn`
- publish beta for `yarn` 
- publish production for `yarn`

**Review by drbobbeaty — COMMENTED** [review]
Seems quite complicated to automate a single command to publish to npmjs...

**Comment by tophercf** [comment]
depends on how you see it - this allows for teams to utilize their preferred tooling, and also allows them to optionally utilize beta builds, which some are.  the command itself is a single call from a dev perspective.

**Comment by drbobbeaty** [comment]
I understand the advantage of the workflow step... I'm just not sure if it's really _saving_ us as much as maintenance of it is going to cost us. 

But I'll approve it.

**Review by drbobbeaty — APPROVED** [review]
I will assume that it _looks_ like it will work, but I haven't checked it. But @tophercf wanted an approval...

**Comment by tophercf** [comment]
thanks - the testing has been done, it's available above and linked reference to the npmjs artifacts

**Pull request merged**
